version: '2.1'
services:
  db_server:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app:v1
    container_name: django_web_server
    restart: always
    ports:
      - 8000:8000
    depends_on:
     -  db_server
